// Code generated by go-swagger; DO NOT EDIT.

package forum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewForumGetTopicForContentParams creates a new ForumGetTopicForContentParams object
// with the default values initialized.
func NewForumGetTopicForContentParams() *ForumGetTopicForContentParams {
	var ()
	return &ForumGetTopicForContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewForumGetTopicForContentParamsWithTimeout creates a new ForumGetTopicForContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewForumGetTopicForContentParamsWithTimeout(timeout time.Duration) *ForumGetTopicForContentParams {
	var ()
	return &ForumGetTopicForContentParams{

		timeout: timeout,
	}
}

// NewForumGetTopicForContentParamsWithContext creates a new ForumGetTopicForContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewForumGetTopicForContentParamsWithContext(ctx context.Context) *ForumGetTopicForContentParams {
	var ()
	return &ForumGetTopicForContentParams{

		Context: ctx,
	}
}

// NewForumGetTopicForContentParamsWithHTTPClient creates a new ForumGetTopicForContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewForumGetTopicForContentParamsWithHTTPClient(client *http.Client) *ForumGetTopicForContentParams {
	var ()
	return &ForumGetTopicForContentParams{
		HTTPClient: client,
	}
}

/*ForumGetTopicForContentParams contains all the parameters to send to the API endpoint
for the forum get topic for content operation typically these are written to a http.Request
*/
type ForumGetTopicForContentParams struct {

	/*ContentID*/
	ContentID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the forum get topic for content params
func (o *ForumGetTopicForContentParams) WithTimeout(timeout time.Duration) *ForumGetTopicForContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the forum get topic for content params
func (o *ForumGetTopicForContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the forum get topic for content params
func (o *ForumGetTopicForContentParams) WithContext(ctx context.Context) *ForumGetTopicForContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the forum get topic for content params
func (o *ForumGetTopicForContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the forum get topic for content params
func (o *ForumGetTopicForContentParams) WithHTTPClient(client *http.Client) *ForumGetTopicForContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the forum get topic for content params
func (o *ForumGetTopicForContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentID adds the contentID to the forum get topic for content params
func (o *ForumGetTopicForContentParams) WithContentID(contentID int64) *ForumGetTopicForContentParams {
	o.SetContentID(contentID)
	return o
}

// SetContentID adds the contentId to the forum get topic for content params
func (o *ForumGetTopicForContentParams) SetContentID(contentID int64) {
	o.ContentID = contentID
}

// WriteToRequest writes these params to a swagger request
func (o *ForumGetTopicForContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contentId
	if err := r.SetPathParam("contentId", swag.FormatInt64(o.ContentID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
