// Code generated by go-swagger; DO NOT EDIT.

package forum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// ForumGetCoreTopicsPagedReader is a Reader for the ForumGetCoreTopicsPaged structure.
type ForumGetCoreTopicsPagedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForumGetCoreTopicsPagedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewForumGetCoreTopicsPagedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewForumGetCoreTopicsPagedOK creates a ForumGetCoreTopicsPagedOK with default headers values
func NewForumGetCoreTopicsPagedOK() *ForumGetCoreTopicsPagedOK {
	return &ForumGetCoreTopicsPagedOK{}
}

/*ForumGetCoreTopicsPagedOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type ForumGetCoreTopicsPagedOK struct {
	Payload *models.ForumGetCoreTopicsPagedOKBody
}

func (o *ForumGetCoreTopicsPagedOK) Error() string {
	return fmt.Sprintf("[GET /Forum/GetCoreTopicsPaged/{page}/{sort}/{quickDate}/{categoryFilter}/][%d] forumGetCoreTopicsPagedOK  %+v", 200, o.Payload)
}

func (o *ForumGetCoreTopicsPagedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ForumGetCoreTopicsPagedOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
