// Code generated by go-swagger; DO NOT EDIT.

package forum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewForumLeaveFireteamThreadParams creates a new ForumLeaveFireteamThreadParams object
// with the default values initialized.
func NewForumLeaveFireteamThreadParams() *ForumLeaveFireteamThreadParams {
	var ()
	return &ForumLeaveFireteamThreadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewForumLeaveFireteamThreadParamsWithTimeout creates a new ForumLeaveFireteamThreadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewForumLeaveFireteamThreadParamsWithTimeout(timeout time.Duration) *ForumLeaveFireteamThreadParams {
	var ()
	return &ForumLeaveFireteamThreadParams{

		timeout: timeout,
	}
}

// NewForumLeaveFireteamThreadParamsWithContext creates a new ForumLeaveFireteamThreadParams object
// with the default values initialized, and the ability to set a context for a request
func NewForumLeaveFireteamThreadParamsWithContext(ctx context.Context) *ForumLeaveFireteamThreadParams {
	var ()
	return &ForumLeaveFireteamThreadParams{

		Context: ctx,
	}
}

// NewForumLeaveFireteamThreadParamsWithHTTPClient creates a new ForumLeaveFireteamThreadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewForumLeaveFireteamThreadParamsWithHTTPClient(client *http.Client) *ForumLeaveFireteamThreadParams {
	var ()
	return &ForumLeaveFireteamThreadParams{
		HTTPClient: client,
	}
}

/*ForumLeaveFireteamThreadParams contains all the parameters to send to the API endpoint
for the forum leave fireteam thread operation typically these are written to a http.Request
*/
type ForumLeaveFireteamThreadParams struct {

	/*TopicID
	  The post id of the recruitment topic you wish to leave.

	*/
	TopicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) WithTimeout(timeout time.Duration) *ForumLeaveFireteamThreadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) WithContext(ctx context.Context) *ForumLeaveFireteamThreadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) WithHTTPClient(client *http.Client) *ForumLeaveFireteamThreadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTopicID adds the topicID to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) WithTopicID(topicID int64) *ForumLeaveFireteamThreadParams {
	o.SetTopicID(topicID)
	return o
}

// SetTopicID adds the topicId to the forum leave fireteam thread params
func (o *ForumLeaveFireteamThreadParams) SetTopicID(topicID int64) {
	o.TopicID = topicID
}

// WriteToRequest writes these params to a swagger request
func (o *ForumLeaveFireteamThreadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param topicId
	if err := r.SetPathParam("topicId", swag.FormatInt64(o.TopicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
