// Code generated by go-swagger; DO NOT EDIT.

package forum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// ForumKickBanFireteamApplicantReader is a Reader for the ForumKickBanFireteamApplicant structure.
type ForumKickBanFireteamApplicantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForumKickBanFireteamApplicantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewForumKickBanFireteamApplicantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewForumKickBanFireteamApplicantOK creates a ForumKickBanFireteamApplicantOK with default headers values
func NewForumKickBanFireteamApplicantOK() *ForumKickBanFireteamApplicantOK {
	return &ForumKickBanFireteamApplicantOK{}
}

/*ForumKickBanFireteamApplicantOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type ForumKickBanFireteamApplicantOK struct {
	Payload *models.ForumKickBanFireteamApplicantOKBody
}

func (o *ForumKickBanFireteamApplicantOK) Error() string {
	return fmt.Sprintf("[POST /Forum/Recruit/KickBan/{topicId}/{targetMembershipId}/][%d] forumKickBanFireteamApplicantOK  %+v", 200, o.Payload)
}

func (o *ForumKickBanFireteamApplicantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ForumKickBanFireteamApplicantOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
