// Code generated by go-swagger; DO NOT EDIT.

package forum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewForumGetPostAndParentAwaitingApprovalParams creates a new ForumGetPostAndParentAwaitingApprovalParams object
// with the default values initialized.
func NewForumGetPostAndParentAwaitingApprovalParams() *ForumGetPostAndParentAwaitingApprovalParams {
	var ()
	return &ForumGetPostAndParentAwaitingApprovalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewForumGetPostAndParentAwaitingApprovalParamsWithTimeout creates a new ForumGetPostAndParentAwaitingApprovalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewForumGetPostAndParentAwaitingApprovalParamsWithTimeout(timeout time.Duration) *ForumGetPostAndParentAwaitingApprovalParams {
	var ()
	return &ForumGetPostAndParentAwaitingApprovalParams{

		timeout: timeout,
	}
}

// NewForumGetPostAndParentAwaitingApprovalParamsWithContext creates a new ForumGetPostAndParentAwaitingApprovalParams object
// with the default values initialized, and the ability to set a context for a request
func NewForumGetPostAndParentAwaitingApprovalParamsWithContext(ctx context.Context) *ForumGetPostAndParentAwaitingApprovalParams {
	var ()
	return &ForumGetPostAndParentAwaitingApprovalParams{

		Context: ctx,
	}
}

// NewForumGetPostAndParentAwaitingApprovalParamsWithHTTPClient creates a new ForumGetPostAndParentAwaitingApprovalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewForumGetPostAndParentAwaitingApprovalParamsWithHTTPClient(client *http.Client) *ForumGetPostAndParentAwaitingApprovalParams {
	var ()
	return &ForumGetPostAndParentAwaitingApprovalParams{
		HTTPClient: client,
	}
}

/*ForumGetPostAndParentAwaitingApprovalParams contains all the parameters to send to the API endpoint
for the forum get post and parent awaiting approval operation typically these are written to a http.Request
*/
type ForumGetPostAndParentAwaitingApprovalParams struct {

	/*ChildPostID*/
	ChildPostID uint64
	/*Showbanned
	  If this value is not null or empty, banned posts are requested to be returned

	*/
	Showbanned *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) WithTimeout(timeout time.Duration) *ForumGetPostAndParentAwaitingApprovalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) WithContext(ctx context.Context) *ForumGetPostAndParentAwaitingApprovalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) WithHTTPClient(client *http.Client) *ForumGetPostAndParentAwaitingApprovalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChildPostID adds the childPostID to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) WithChildPostID(childPostID uint64) *ForumGetPostAndParentAwaitingApprovalParams {
	o.SetChildPostID(childPostID)
	return o
}

// SetChildPostID adds the childPostId to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) SetChildPostID(childPostID uint64) {
	o.ChildPostID = childPostID
}

// WithShowbanned adds the showbanned to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) WithShowbanned(showbanned *string) *ForumGetPostAndParentAwaitingApprovalParams {
	o.SetShowbanned(showbanned)
	return o
}

// SetShowbanned adds the showbanned to the forum get post and parent awaiting approval params
func (o *ForumGetPostAndParentAwaitingApprovalParams) SetShowbanned(showbanned *string) {
	o.Showbanned = showbanned
}

// WriteToRequest writes these params to a swagger request
func (o *ForumGetPostAndParentAwaitingApprovalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param childPostId
	if err := r.SetPathParam("childPostId", swag.FormatUint64(o.ChildPostID)); err != nil {
		return err
	}

	if o.Showbanned != nil {

		// query param showbanned
		var qrShowbanned string
		if o.Showbanned != nil {
			qrShowbanned = *o.Showbanned
		}
		qShowbanned := qrShowbanned
		if qShowbanned != "" {
			if err := r.SetQueryParam("showbanned", qShowbanned); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
