// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// Destiny2GetActivityHistoryReader is a Reader for the Destiny2GetActivityHistory structure.
type Destiny2GetActivityHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Destiny2GetActivityHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDestiny2GetActivityHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDestiny2GetActivityHistoryOK creates a Destiny2GetActivityHistoryOK with default headers values
func NewDestiny2GetActivityHistoryOK() *Destiny2GetActivityHistoryOK {
	return &Destiny2GetActivityHistoryOK{}
}

/*Destiny2GetActivityHistoryOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type Destiny2GetActivityHistoryOK struct {
	Payload *models.Destiny2GetActivityHistoryOKBody
}

func (o *Destiny2GetActivityHistoryOK) Error() string {
	return fmt.Sprintf("[GET /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/][%d] destiny2GetActivityHistoryOK  %+v", 200, o.Payload)
}

func (o *Destiny2GetActivityHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Destiny2GetActivityHistoryOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
