// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// Destiny2GetLeaderboardsForCharacterReader is a Reader for the Destiny2GetLeaderboardsForCharacter structure.
type Destiny2GetLeaderboardsForCharacterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Destiny2GetLeaderboardsForCharacterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDestiny2GetLeaderboardsForCharacterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDestiny2GetLeaderboardsForCharacterOK creates a Destiny2GetLeaderboardsForCharacterOK with default headers values
func NewDestiny2GetLeaderboardsForCharacterOK() *Destiny2GetLeaderboardsForCharacterOK {
	return &Destiny2GetLeaderboardsForCharacterOK{}
}

/*Destiny2GetLeaderboardsForCharacterOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type Destiny2GetLeaderboardsForCharacterOK struct {
	Payload *models.Destiny2GetLeaderboardsForCharacterOKBody
}

func (o *Destiny2GetLeaderboardsForCharacterOK) Error() string {
	return fmt.Sprintf("[GET /Destiny2/Stats/Leaderboards/{membershipType}/{destinyMembershipId}/{characterId}/][%d] destiny2GetLeaderboardsForCharacterOK  %+v", 200, o.Payload)
}

func (o *Destiny2GetLeaderboardsForCharacterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Destiny2GetLeaderboardsForCharacterOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
