// Code generated by go-swagger; DO NOT EDIT.

package destiny2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDestiny2GetDestinyManifestParams creates a new Destiny2GetDestinyManifestParams object
// with the default values initialized.
func NewDestiny2GetDestinyManifestParams() *Destiny2GetDestinyManifestParams {

	return &Destiny2GetDestinyManifestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDestiny2GetDestinyManifestParamsWithTimeout creates a new Destiny2GetDestinyManifestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDestiny2GetDestinyManifestParamsWithTimeout(timeout time.Duration) *Destiny2GetDestinyManifestParams {

	return &Destiny2GetDestinyManifestParams{

		timeout: timeout,
	}
}

// NewDestiny2GetDestinyManifestParamsWithContext creates a new Destiny2GetDestinyManifestParams object
// with the default values initialized, and the ability to set a context for a request
func NewDestiny2GetDestinyManifestParamsWithContext(ctx context.Context) *Destiny2GetDestinyManifestParams {

	return &Destiny2GetDestinyManifestParams{

		Context: ctx,
	}
}

// NewDestiny2GetDestinyManifestParamsWithHTTPClient creates a new Destiny2GetDestinyManifestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDestiny2GetDestinyManifestParamsWithHTTPClient(client *http.Client) *Destiny2GetDestinyManifestParams {

	return &Destiny2GetDestinyManifestParams{
		HTTPClient: client,
	}
}

/*Destiny2GetDestinyManifestParams contains all the parameters to send to the API endpoint
for the destiny2 get destiny manifest operation typically these are written to a http.Request
*/
type Destiny2GetDestinyManifestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) WithTimeout(timeout time.Duration) *Destiny2GetDestinyManifestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) WithContext(ctx context.Context) *Destiny2GetDestinyManifestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) WithHTTPClient(client *http.Client) *Destiny2GetDestinyManifestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the destiny2 get destiny manifest params
func (o *Destiny2GetDestinyManifestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *Destiny2GetDestinyManifestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
