// Code generated by go-swagger; DO NOT EDIT.

package destiny2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDestiny2EquipItemParams creates a new Destiny2EquipItemParams object
// with the default values initialized.
func NewDestiny2EquipItemParams() *Destiny2EquipItemParams {

	return &Destiny2EquipItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDestiny2EquipItemParamsWithTimeout creates a new Destiny2EquipItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDestiny2EquipItemParamsWithTimeout(timeout time.Duration) *Destiny2EquipItemParams {

	return &Destiny2EquipItemParams{

		timeout: timeout,
	}
}

// NewDestiny2EquipItemParamsWithContext creates a new Destiny2EquipItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewDestiny2EquipItemParamsWithContext(ctx context.Context) *Destiny2EquipItemParams {

	return &Destiny2EquipItemParams{

		Context: ctx,
	}
}

// NewDestiny2EquipItemParamsWithHTTPClient creates a new Destiny2EquipItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDestiny2EquipItemParamsWithHTTPClient(client *http.Client) *Destiny2EquipItemParams {

	return &Destiny2EquipItemParams{
		HTTPClient: client,
	}
}

/*Destiny2EquipItemParams contains all the parameters to send to the API endpoint
for the destiny2 equip item operation typically these are written to a http.Request
*/
type Destiny2EquipItemParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the destiny2 equip item params
func (o *Destiny2EquipItemParams) WithTimeout(timeout time.Duration) *Destiny2EquipItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the destiny2 equip item params
func (o *Destiny2EquipItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the destiny2 equip item params
func (o *Destiny2EquipItemParams) WithContext(ctx context.Context) *Destiny2EquipItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the destiny2 equip item params
func (o *Destiny2EquipItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the destiny2 equip item params
func (o *Destiny2EquipItemParams) WithHTTPClient(client *http.Client) *Destiny2EquipItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the destiny2 equip item params
func (o *Destiny2EquipItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *Destiny2EquipItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
