// Code generated by go-swagger; DO NOT EDIT.

package destiny2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// Destiny2GetCharacterReader is a Reader for the Destiny2GetCharacter structure.
type Destiny2GetCharacterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Destiny2GetCharacterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDestiny2GetCharacterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDestiny2GetCharacterOK creates a Destiny2GetCharacterOK with default headers values
func NewDestiny2GetCharacterOK() *Destiny2GetCharacterOK {
	return &Destiny2GetCharacterOK{}
}

/*Destiny2GetCharacterOK handles this case with default header values.

The response contract for GetDestinyCharacter, with components that can be returned for character and item-level data.
*/
type Destiny2GetCharacterOK struct {
	Payload *models.Destiny2GetCharacterOKBody
}

func (o *Destiny2GetCharacterOK) Error() string {
	return fmt.Sprintf("[GET /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/][%d] destiny2GetCharacterOK  %+v", 200, o.Payload)
}

func (o *Destiny2GetCharacterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Destiny2GetCharacterOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
