// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// GroupV2RequestGroupMembershipReader is a Reader for the GroupV2RequestGroupMembership structure.
type GroupV2RequestGroupMembershipReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupV2RequestGroupMembershipReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGroupV2RequestGroupMembershipOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupV2RequestGroupMembershipOK creates a GroupV2RequestGroupMembershipOK with default headers values
func NewGroupV2RequestGroupMembershipOK() *GroupV2RequestGroupMembershipOK {
	return &GroupV2RequestGroupMembershipOK{}
}

/*GroupV2RequestGroupMembershipOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type GroupV2RequestGroupMembershipOK struct {
	Payload *models.GroupV2RequestGroupMembershipOKBody
}

func (o *GroupV2RequestGroupMembershipOK) Error() string {
	return fmt.Sprintf("[POST /GroupV2/{groupId}/Members/Apply/{membershipType}/][%d] groupV2RequestGroupMembershipOK  %+v", 200, o.Payload)
}

func (o *GroupV2RequestGroupMembershipOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupV2RequestGroupMembershipOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
