// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGroupV2ApprovePendingForListParams creates a new GroupV2ApprovePendingForListParams object
// with the default values initialized.
func NewGroupV2ApprovePendingForListParams() *GroupV2ApprovePendingForListParams {
	var ()
	return &GroupV2ApprovePendingForListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGroupV2ApprovePendingForListParamsWithTimeout creates a new GroupV2ApprovePendingForListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGroupV2ApprovePendingForListParamsWithTimeout(timeout time.Duration) *GroupV2ApprovePendingForListParams {
	var ()
	return &GroupV2ApprovePendingForListParams{

		timeout: timeout,
	}
}

// NewGroupV2ApprovePendingForListParamsWithContext creates a new GroupV2ApprovePendingForListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGroupV2ApprovePendingForListParamsWithContext(ctx context.Context) *GroupV2ApprovePendingForListParams {
	var ()
	return &GroupV2ApprovePendingForListParams{

		Context: ctx,
	}
}

// NewGroupV2ApprovePendingForListParamsWithHTTPClient creates a new GroupV2ApprovePendingForListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGroupV2ApprovePendingForListParamsWithHTTPClient(client *http.Client) *GroupV2ApprovePendingForListParams {
	var ()
	return &GroupV2ApprovePendingForListParams{
		HTTPClient: client,
	}
}

/*GroupV2ApprovePendingForListParams contains all the parameters to send to the API endpoint
for the group v2 approve pending for list operation typically these are written to a http.Request
*/
type GroupV2ApprovePendingForListParams struct {

	/*GroupID
	  ID of the group.

	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) WithTimeout(timeout time.Duration) *GroupV2ApprovePendingForListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) WithContext(ctx context.Context) *GroupV2ApprovePendingForListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) WithHTTPClient(client *http.Client) *GroupV2ApprovePendingForListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) WithGroupID(groupID int64) *GroupV2ApprovePendingForListParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the group v2 approve pending for list params
func (o *GroupV2ApprovePendingForListParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GroupV2ApprovePendingForListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
