// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// GroupV2DenyPendingForListReader is a Reader for the GroupV2DenyPendingForList structure.
type GroupV2DenyPendingForListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupV2DenyPendingForListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGroupV2DenyPendingForListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupV2DenyPendingForListOK creates a GroupV2DenyPendingForListOK with default headers values
func NewGroupV2DenyPendingForListOK() *GroupV2DenyPendingForListOK {
	return &GroupV2DenyPendingForListOK{}
}

/*GroupV2DenyPendingForListOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type GroupV2DenyPendingForListOK struct {
	Payload *models.GroupV2DenyPendingForListOKBody
}

func (o *GroupV2DenyPendingForListOK) Error() string {
	return fmt.Sprintf("[POST /GroupV2/{groupId}/Members/DenyList/][%d] groupV2DenyPendingForListOK  %+v", 200, o.Payload)
}

func (o *GroupV2DenyPendingForListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupV2DenyPendingForListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
