// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGroupV2DenyAllPendingParams creates a new GroupV2DenyAllPendingParams object
// with the default values initialized.
func NewGroupV2DenyAllPendingParams() *GroupV2DenyAllPendingParams {
	var ()
	return &GroupV2DenyAllPendingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGroupV2DenyAllPendingParamsWithTimeout creates a new GroupV2DenyAllPendingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGroupV2DenyAllPendingParamsWithTimeout(timeout time.Duration) *GroupV2DenyAllPendingParams {
	var ()
	return &GroupV2DenyAllPendingParams{

		timeout: timeout,
	}
}

// NewGroupV2DenyAllPendingParamsWithContext creates a new GroupV2DenyAllPendingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGroupV2DenyAllPendingParamsWithContext(ctx context.Context) *GroupV2DenyAllPendingParams {
	var ()
	return &GroupV2DenyAllPendingParams{

		Context: ctx,
	}
}

// NewGroupV2DenyAllPendingParamsWithHTTPClient creates a new GroupV2DenyAllPendingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGroupV2DenyAllPendingParamsWithHTTPClient(client *http.Client) *GroupV2DenyAllPendingParams {
	var ()
	return &GroupV2DenyAllPendingParams{
		HTTPClient: client,
	}
}

/*GroupV2DenyAllPendingParams contains all the parameters to send to the API endpoint
for the group v2 deny all pending operation typically these are written to a http.Request
*/
type GroupV2DenyAllPendingParams struct {

	/*GroupID
	  ID of the group.

	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) WithTimeout(timeout time.Duration) *GroupV2DenyAllPendingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) WithContext(ctx context.Context) *GroupV2DenyAllPendingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) WithHTTPClient(client *http.Client) *GroupV2DenyAllPendingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) WithGroupID(groupID int64) *GroupV2DenyAllPendingParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the group v2 deny all pending params
func (o *GroupV2DenyAllPendingParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GroupV2DenyAllPendingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
