// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/zhirsch/destiny2-api/models"
)

// GroupV2GetBannedMembersOfGroupReader is a Reader for the GroupV2GetBannedMembersOfGroup structure.
type GroupV2GetBannedMembersOfGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupV2GetBannedMembersOfGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGroupV2GetBannedMembersOfGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupV2GetBannedMembersOfGroupOK creates a GroupV2GetBannedMembersOfGroupOK with default headers values
func NewGroupV2GetBannedMembersOfGroupOK() *GroupV2GetBannedMembersOfGroupOK {
	return &GroupV2GetBannedMembersOfGroupOK{}
}

/*GroupV2GetBannedMembersOfGroupOK handles this case with default header values.

Look at the Response property for more information about the nature of this response
*/
type GroupV2GetBannedMembersOfGroupOK struct {
	Payload *models.GroupV2GetBannedMembersOfGroupOKBody
}

func (o *GroupV2GetBannedMembersOfGroupOK) Error() string {
	return fmt.Sprintf("[GET /GroupV2/{groupId}/Banned/][%d] groupV2GetBannedMembersOfGroupOK  %+v", 200, o.Payload)
}

func (o *GroupV2GetBannedMembersOfGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupV2GetBannedMembersOfGroupOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
