// Code generated by go-swagger; DO NOT EDIT.

package group_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGroupV2IndividualGroupInviteCancelParams creates a new GroupV2IndividualGroupInviteCancelParams object
// with the default values initialized.
func NewGroupV2IndividualGroupInviteCancelParams() *GroupV2IndividualGroupInviteCancelParams {
	var ()
	return &GroupV2IndividualGroupInviteCancelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGroupV2IndividualGroupInviteCancelParamsWithTimeout creates a new GroupV2IndividualGroupInviteCancelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGroupV2IndividualGroupInviteCancelParamsWithTimeout(timeout time.Duration) *GroupV2IndividualGroupInviteCancelParams {
	var ()
	return &GroupV2IndividualGroupInviteCancelParams{

		timeout: timeout,
	}
}

// NewGroupV2IndividualGroupInviteCancelParamsWithContext creates a new GroupV2IndividualGroupInviteCancelParams object
// with the default values initialized, and the ability to set a context for a request
func NewGroupV2IndividualGroupInviteCancelParamsWithContext(ctx context.Context) *GroupV2IndividualGroupInviteCancelParams {
	var ()
	return &GroupV2IndividualGroupInviteCancelParams{

		Context: ctx,
	}
}

// NewGroupV2IndividualGroupInviteCancelParamsWithHTTPClient creates a new GroupV2IndividualGroupInviteCancelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGroupV2IndividualGroupInviteCancelParamsWithHTTPClient(client *http.Client) *GroupV2IndividualGroupInviteCancelParams {
	var ()
	return &GroupV2IndividualGroupInviteCancelParams{
		HTTPClient: client,
	}
}

/*GroupV2IndividualGroupInviteCancelParams contains all the parameters to send to the API endpoint
for the group v2 individual group invite cancel operation typically these are written to a http.Request
*/
type GroupV2IndividualGroupInviteCancelParams struct {

	/*GroupID
	  ID of the group you would like to join.

	*/
	GroupID int64
	/*MembershipID
	  Membership id of the account being cancelled.

	*/
	MembershipID int64
	/*MembershipType
	  MembershipType of the account being cancelled.

	*/
	MembershipType int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithTimeout(timeout time.Duration) *GroupV2IndividualGroupInviteCancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithContext(ctx context.Context) *GroupV2IndividualGroupInviteCancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithHTTPClient(client *http.Client) *GroupV2IndividualGroupInviteCancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithGroupID(groupID int64) *GroupV2IndividualGroupInviteCancelParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WithMembershipID adds the membershipID to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithMembershipID(membershipID int64) *GroupV2IndividualGroupInviteCancelParams {
	o.SetMembershipID(membershipID)
	return o
}

// SetMembershipID adds the membershipId to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetMembershipID(membershipID int64) {
	o.MembershipID = membershipID
}

// WithMembershipType adds the membershipType to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) WithMembershipType(membershipType int32) *GroupV2IndividualGroupInviteCancelParams {
	o.SetMembershipType(membershipType)
	return o
}

// SetMembershipType adds the membershipType to the group v2 individual group invite cancel params
func (o *GroupV2IndividualGroupInviteCancelParams) SetMembershipType(membershipType int32) {
	o.MembershipType = membershipType
}

// WriteToRequest writes these params to a swagger request
func (o *GroupV2IndividualGroupInviteCancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	// path param membershipId
	if err := r.SetPathParam("membershipId", swag.FormatInt64(o.MembershipID)); err != nil {
		return err
	}

	// path param membershipType
	if err := r.SetPathParam("membershipType", swag.FormatInt32(o.MembershipType)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
