// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyDefinitionsDestinyItemPerkEntryDefinition An intrinsic perk on an item, and the requirements for it to be activated.
// swagger:model Destiny.Definitions.DestinyItemPerkEntryDefinition

type DestinyDefinitionsDestinyItemPerkEntryDefinition struct {

	// A hash identifier for the DestinySandboxPerkDefinition being provided on the item.
	PerkHash uint32 `json:"perkHash,omitempty"`

	// If this perk is not active, this is the string to show for why it's not providing its benefits.
	RequirementDisplayString string `json:"requirementDisplayString,omitempty"`
}

/* polymorph Destiny.Definitions.DestinyItemPerkEntryDefinition perkHash false */

/* polymorph Destiny.Definitions.DestinyItemPerkEntryDefinition requirementDisplayString false */

// Validate validates this destiny definitions destiny item perk entry definition
func (m *DestinyDefinitionsDestinyItemPerkEntryDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyItemPerkEntryDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyItemPerkEntryDefinition) UnmarshalBinary(b []byte) error {
	var res DestinyDefinitionsDestinyItemPerkEntryDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
