// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter destiny historical stats destiny historical stats per character
// swagger:model Destiny.HistoricalStats.DestinyHistoricalStatsPerCharacter

type DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter struct {

	// character Id
	CharacterID int64 `json:"characterId,omitempty"`

	// deleted
	Deleted bool `json:"deleted,omitempty"`

	// merged
	Merged *DestinyHistoricalStatsDestinyHistoricalStatsByPeriod `json:"merged,omitempty"`

	// results
	Results DestinyHistoricalStatsDestinyHistoricalStatsPerCharacterResults `json:"results,omitempty"`
}

/* polymorph Destiny.HistoricalStats.DestinyHistoricalStatsPerCharacter characterId false */

/* polymorph Destiny.HistoricalStats.DestinyHistoricalStatsPerCharacter deleted false */

/* polymorph Destiny.HistoricalStats.DestinyHistoricalStatsPerCharacter merged false */

/* polymorph Destiny.HistoricalStats.DestinyHistoricalStatsPerCharacter results false */

// Validate validates this destiny historical stats destiny historical stats per character
func (m *DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMerged(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter) validateMerged(formats strfmt.Registry) error {

	if swag.IsZero(m.Merged) { // not required
		return nil
	}

	if m.Merged != nil {

		if err := m.Merged.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("merged")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter) UnmarshalBinary(b []byte) error {
	var res DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
