// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyHistoricalStatsDestinyAggregateActivityStatsValues Collection of stats for the player in this activity.
// swagger:model destinyHistoricalStatsDestinyAggregateActivityStatsValues

type DestinyHistoricalStatsDestinyAggregateActivityStatsValues map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue

// Validate validates this destiny historical stats destiny aggregate activity stats values
func (m DestinyHistoricalStatsDestinyAggregateActivityStatsValues) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", DestinyHistoricalStatsDestinyAggregateActivityStatsValues(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
