// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionActivities The full set of all possible "conceptual activities" that are related to this Milestone. Tiers or alternative modes of play within these conceptual activities will be defined as sub-entities. Keyed by the Conceptual Activity Hash. Use the key to look up DestinyActivityDefinition.
// swagger:model destinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionActivities

type DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionActivities map[string]DestinyDefinitionsMilestonesDestinyMilestoneActivityDefinition

// Validate validates this destiny definitions milestones destiny milestone quest definition activities
func (m DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionActivities) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionActivities(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
