// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyDamageType destiny damage type
// swagger:model Destiny.DamageType

type DestinyDamageType int32

// for schema
var destinyDamageTypeEnum []interface{}

func init() {
	var res []DestinyDamageType
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyDamageTypeEnum = append(destinyDamageTypeEnum, v)
	}
}

func (m DestinyDamageType) validateDestinyDamageTypeEnum(path, location string, value DestinyDamageType) error {
	if err := validate.Enum(path, location, value, destinyDamageTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny damage type
func (m DestinyDamageType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyDamageTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
