// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Destiny2GetLeaderboardsOKBodyResponseAdditionalProperties destiny2 get leaderboards o k body response additional properties
// swagger:model destiny2GetLeaderboardsOKBodyResponseAdditionalProperties

type Destiny2GetLeaderboardsOKBodyResponseAdditionalProperties map[string]DestinyHistoricalStatsDestinyLeaderboard

// Validate validates this destiny2 get leaderboards o k body response additional properties
func (m Destiny2GetLeaderboardsOKBodyResponseAdditionalProperties) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", Destiny2GetLeaderboardsOKBodyResponseAdditionalProperties(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
