// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition destiny definitions director destiny linked graph entry definition
// swagger:model Destiny.Definitions.Director.DestinyLinkedGraphEntryDefinition

type DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition struct {

	// activity graph hash
	ActivityGraphHash uint32 `json:"activityGraphHash,omitempty"`
}

/* polymorph Destiny.Definitions.Director.DestinyLinkedGraphEntryDefinition activityGraphHash false */

// Validate validates this destiny definitions director destiny linked graph entry definition
func (m *DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition) UnmarshalBinary(b []byte) error {
	var res DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
