// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyDefinitionsDestinyItemStatBlockDefinitionStats If you are looking for precomputed values for the stats on a weapon, this is where they are stored. Technically these are the "Display" stat values. Please see DestinyStatsDefinition for what Display Stat Values means, it's a very long story... but essentially these are the closest values BNet can get to the item stats that you see in-game.
// These stats are keyed by the DestinyStatDefinition's hash identifier for the stat that's found on the item.
// swagger:model destinyDefinitionsDestinyItemStatBlockDefinitionStats

type DestinyDefinitionsDestinyItemStatBlockDefinitionStats map[string]DestinyDefinitionsDestinyInventoryItemStatDefinition

// Validate validates this destiny definitions destiny item stat block definition stats
func (m DestinyDefinitionsDestinyItemStatBlockDefinitionStats) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", DestinyDefinitionsDestinyItemStatBlockDefinitionStats(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
