// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyDefinitionsDestinyMaterialRequirementSetDefinition Represent a set of material requirements: Items that either need to be owned or need to be consumed in order to perform an action.
// A variety of other entities refer to these as gatekeepers and payments for actions that can be performed in game.
// swagger:model Destiny.Definitions.DestinyMaterialRequirementSetDefinition

type DestinyDefinitionsDestinyMaterialRequirementSetDefinition struct {

	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
	// When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash uint32 `json:"hash,omitempty"`

	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`

	// materials
	Materials DestinyDefinitionsDestinyMaterialRequirementSetDefinitionMaterials `json:"materials"`

	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}

/* polymorph Destiny.Definitions.DestinyMaterialRequirementSetDefinition hash false */

/* polymorph Destiny.Definitions.DestinyMaterialRequirementSetDefinition index false */

/* polymorph Destiny.Definitions.DestinyMaterialRequirementSetDefinition materials false */

/* polymorph Destiny.Definitions.DestinyMaterialRequirementSetDefinition redacted false */

// Validate validates this destiny definitions destiny material requirement set definition
func (m *DestinyDefinitionsDestinyMaterialRequirementSetDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyMaterialRequirementSetDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyMaterialRequirementSetDefinition) UnmarshalBinary(b []byte) error {
	var res DestinyDefinitionsDestinyMaterialRequirementSetDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
