// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyTransferStatuses Whether you can transfer an item, and why not if you can't.
// swagger:model Destiny.TransferStatuses

type DestinyTransferStatuses int32

// for schema
var destinyTransferStatusesEnum []interface{}

func init() {
	var res []DestinyTransferStatuses
	if err := json.Unmarshal([]byte(`[0,1,2,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyTransferStatusesEnum = append(destinyTransferStatusesEnum, v)
	}
}

func (m DestinyTransferStatuses) validateDestinyTransferStatusesEnum(path, location string, value DestinyTransferStatuses) error {
	if err := validate.Enum(path, location, value, destinyTransferStatusesEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny transfer statuses
func (m DestinyTransferStatuses) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyTransferStatusesEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
