// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances destiny definitions destiny talent node step weapon performances
// swagger:model Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances

type DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances int32

// for schema
var destinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum []interface{}

func init() {
	var res []DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances
	if err := json.Unmarshal([]byte(`[0,1,2,4,8,16,32,64,128,256,512,1024,2048,4096,8191]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum = append(destinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum, v)
	}
}

func (m DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances) validateDestinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum(path, location string, value DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances) error {
	if err := validate.Enum(path, location, value, destinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny definitions destiny talent node step weapon performances
func (m DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyDefinitionsDestinyTalentNodeStepWeaponPerformancesEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
