// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData destiny historical stats destiny post game carnage report extended data
// swagger:model Destiny.HistoricalStats.DestinyPostGameCarnageReportExtendedData

type DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData struct {

	// values
	Values DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedDataValues `json:"values,omitempty"`

	// weapons
	Weapons DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedDataWeapons `json:"weapons"`
}

/* polymorph Destiny.HistoricalStats.DestinyPostGameCarnageReportExtendedData values false */

/* polymorph Destiny.HistoricalStats.DestinyPostGameCarnageReportExtendedData weapons false */

// Validate validates this destiny historical stats destiny post game carnage report extended data
func (m *DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData) UnmarshalBinary(b []byte) error {
	var res DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
