// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyConfigDestinyManifest DestinyManifest is the external-facing contract for just the properties needed by those calling the Destiny Platform.
// swagger:model Destiny.Config.DestinyManifest

type DestinyConfigDestinyManifest struct {

	// mobile asset content path
	MobileAssetContentPath string `json:"mobileAssetContentPath,omitempty"`

	// mobile clan banner database path
	MobileClanBannerDatabasePath string `json:"mobileClanBannerDatabasePath,omitempty"`

	// mobile gear asset data bases
	MobileGearAssetDataBases DestinyConfigDestinyManifestMobileGearAssetDataBases `json:"mobileGearAssetDataBases"`

	// mobile gear c d n
	MobileGearCDN map[string]string `json:"mobileGearCDN,omitempty"`

	// mobile world content paths
	MobileWorldContentPaths map[string]string `json:"mobileWorldContentPaths,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

/* polymorph Destiny.Config.DestinyManifest mobileAssetContentPath false */

/* polymorph Destiny.Config.DestinyManifest mobileClanBannerDatabasePath false */

/* polymorph Destiny.Config.DestinyManifest mobileGearAssetDataBases false */

/* polymorph Destiny.Config.DestinyManifest mobileGearCDN false */

/* polymorph Destiny.Config.DestinyManifest mobileWorldContentPaths false */

/* polymorph Destiny.Config.DestinyManifest version false */

// Validate validates this destiny config destiny manifest
func (m *DestinyConfigDestinyManifest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyConfigDestinyManifest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyConfigDestinyManifest) UnmarshalBinary(b []byte) error {
	var res DestinyConfigDestinyManifest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
