// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyHistoricalStatsDefinitionsPeriodType destiny historical stats definitions period type
// swagger:model Destiny.HistoricalStats.Definitions.PeriodType

type DestinyHistoricalStatsDefinitionsPeriodType int32

// for schema
var destinyHistoricalStatsDefinitionsPeriodTypeEnum []interface{}

func init() {
	var res []DestinyHistoricalStatsDefinitionsPeriodType
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyHistoricalStatsDefinitionsPeriodTypeEnum = append(destinyHistoricalStatsDefinitionsPeriodTypeEnum, v)
	}
}

func (m DestinyHistoricalStatsDefinitionsPeriodType) validateDestinyHistoricalStatsDefinitionsPeriodTypeEnum(path, location string, value DestinyHistoricalStatsDefinitionsPeriodType) error {
	if err := validate.Enum(path, location, value, destinyHistoricalStatsDefinitionsPeriodTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny historical stats definitions period type
func (m DestinyHistoricalStatsDefinitionsPeriodType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyHistoricalStatsDefinitionsPeriodTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
