// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyHistoricalStatsDestinyLeaderboard destiny historical stats destiny leaderboard
// swagger:model Destiny.HistoricalStats.DestinyLeaderboard

type DestinyHistoricalStatsDestinyLeaderboard struct {

	// entries
	Entries DestinyHistoricalStatsDestinyLeaderboardEntries `json:"entries"`

	// stat Id
	StatID string `json:"statId,omitempty"`
}

/* polymorph Destiny.HistoricalStats.DestinyLeaderboard entries false */

/* polymorph Destiny.HistoricalStats.DestinyLeaderboard statId false */

// Validate validates this destiny historical stats destiny leaderboard
func (m *DestinyHistoricalStatsDestinyLeaderboard) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyLeaderboard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyHistoricalStatsDestinyLeaderboard) UnmarshalBinary(b []byte) error {
	var res DestinyHistoricalStatsDestinyLeaderboard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
