// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyHistoricalStatsDefinitionsDestinyStatsGroupType destiny historical stats definitions destiny stats group type
// swagger:model Destiny.HistoricalStats.Definitions.DestinyStatsGroupType

type DestinyHistoricalStatsDefinitionsDestinyStatsGroupType int32

// for schema
var destinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum []interface{}

func init() {
	var res []DestinyHistoricalStatsDefinitionsDestinyStatsGroupType
	if err := json.Unmarshal([]byte(`[0,1,2,3,100,101,102,103,104]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum = append(destinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum, v)
	}
}

func (m DestinyHistoricalStatsDefinitionsDestinyStatsGroupType) validateDestinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum(path, location string, value DestinyHistoricalStatsDefinitionsDestinyStatsGroupType) error {
	if err := validate.Enum(path, location, value, destinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny historical stats definitions destiny stats group type
func (m DestinyHistoricalStatsDefinitionsDestinyStatsGroupType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyHistoricalStatsDefinitionsDestinyStatsGroupTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
