// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectives Sometimes, you have items in your inventory that don't have instances, but still have Objective information. This provides you that objective information for uninstanced items.
// This dictionary is keyed by the item's hash: which you can use to look up the name and description for the overall task(s) implied by the objective. The value is the list of objectives for this item, and their statuses.
// swagger:model destinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectives

type DestinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectives map[string]DestinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectivesAdditionalProperties

// Validate validates this destiny entities characters destiny character progression component uninstanced item objectives
func (m DestinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectives) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", DestinyEntitiesCharactersDestinyCharacterProgressionComponentUninstancedItemObjectives(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
