// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Destiny2GetPublicMilestonesOKBodyResponse destiny2 get public milestones o k body response
// swagger:model destiny2GetPublicMilestonesOKBodyResponse

type Destiny2GetPublicMilestonesOKBodyResponse map[string]DestinyMilestonesDestinyPublicMilestone

// Validate validates this destiny2 get public milestones o k body response
func (m Destiny2GetPublicMilestonesOKBodyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", Destiny2GetPublicMilestonesOKBodyResponse(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
