// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DestinyDestinyComponentType destiny destiny component type
// swagger:model Destiny.DestinyComponentType

type DestinyDestinyComponentType int32

// for schema
var destinyDestinyComponentTypeEnum []interface{}

func init() {
	var res []DestinyDestinyComponentType
	if err := json.Unmarshal([]byte(`[0,100,101,102,103,200,201,202,203,204,205,300,301,302,303,304,305,306,307,308,400,401,402,500]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		destinyDestinyComponentTypeEnum = append(destinyDestinyComponentTypeEnum, v)
	}
}

func (m DestinyDestinyComponentType) validateDestinyDestinyComponentTypeEnum(path, location string, value DestinyDestinyComponentType) error {
	if err := validate.Enum(path, location, value, destinyDestinyComponentTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this destiny destiny component type
func (m DestinyDestinyComponentType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDestinyDestinyComponentTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
