// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyActivitiesDestinyPublicActivityStatusRewardTooltipItems If the activity itself provides any specific "mock" rewards, this will be the items and their quantity.
// Why "mock", you ask? Because these are the rewards as they are represented in the tooltip of the Activity.
// These are often pointers to fake items that look good in a tooltip, but represent an abstract concept of what you will get for a reward rather than the specific items you may obtain.
// swagger:model destinyActivitiesDestinyPublicActivityStatusRewardTooltipItems

type DestinyActivitiesDestinyPublicActivityStatusRewardTooltipItems []*DestinyDestinyItemQuantity

// Validate validates this destiny activities destiny public activity status reward tooltip items
func (m DestinyActivitiesDestinyPublicActivityStatusRewardTooltipItems) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
