// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyDestinyTalentNode I see you've come to find out more about Talent Nodes. I'm so sorry. Talent Nodes are the conceptual, visual nodes that appear on Talent Grids. Talent Grids, in Destiny 1, were found on almost every instanced item: they had Nodes that could be activated to change the properties of the item. In Destiny 2, Talent Grids only exist for Builds/Subclasses, and while the basic concept is the same (Nodes can be activated once you've gained sufficient Experience on the Item, and provide effects), there are some new concepts from Destiny 1. Examine DestinyTalentGridDefinition and its subordinates for more information. This is the "Live" information for the current status of a Talent Node on a specific item. Talent Nodes have many Steps, but only one can be active at any one time: and it is the Step that determines both the visual and the game state-changing properties that the Node provides. Examine this and DestinyTalentNodeStepDefinition carefully. *IMPORTANT NOTE* Talent Nodes are, unfortunately, Content Version DEPENDENT. Though they refer to hashes for Nodes and Steps, those hashes are not guaranteed to be immutable across content versions. This is a source of great exasperation for me, but as a result anyone using Talent Grid data must ensure that the content version of their static content matches that of the server responses before showing or making decisions based on talent grid data.
// swagger:model Destiny.DestinyTalentNode

type DestinyDestinyTalentNode struct {

	// The progression level required on the Talent Grid in order to be able to activate this talent node. Talent Grids have their own Progression - similar to Character Level, but in this case it is experience related to the item itself.
	ActivationGridLevel int32 `json:"activationGridLevel,omitempty"`

	// Whether or not the talent node is actually visible in the game's UI. Whether you want to show it in your own UI is up to you! I'm not gonna tell you who to sock it to.
	Hidden bool `json:"hidden,omitempty"`

	// If true, the node is activated: it's current step then provides its benefits.
	IsActivated bool `json:"isActivated,omitempty"`

	// materials to upgrade
	MaterialsToUpgrade DestinyDestinyTalentNodeMaterialsToUpgrade `json:"materialsToUpgrade"`

	// The hash of the Talent Node being referred to (in DestinyTalentGridDefinition.nodes). Deceptively CONTENT VERSION DEPENDENT. We have no guarantee of the hash's immutability between content versions.
	NodeHash uint32 `json:"nodeHash,omitempty"`

	// The index of the Talent Node being referred to (an index into DestinyTalentGridDefinition.nodes[]). CONTENT VERSION DEPENDENT.
	NodeIndex int32 `json:"nodeIndex,omitempty"`

	// This property has some history. A talent grid can provide stats on both the item it's related to and the character equipping the item. This returns data about those stat bonuses.
	NodeStatsBlock *DestinyDestinyTalentNodeStatBlock `json:"nodeStatsBlock,omitempty"`

	// If you want to show a progress bar or circle for how close this talent node is to being activate-able, this is the percentage to show. It follows the node's underlying rules about when the progress bar should first show up, and when it should be filled.
	ProgressPercent float32 `json:"progressPercent,omitempty"`

	// An DestinyTalentNodeState enum value indicating the node's state: whether it can be activated or swapped, and why not if neither can be performed.
	State DestinyDestinyTalentNodeState `json:"state,omitempty"`

	// The currently relevant Step for the node. It is this step that has rendering data for the node and the benefits that are provided if the node is activated. (the actual rules for benefits provided are extremely complicated in theory, but with how Talent Grids are being used in Destiny 2 you don't have to worry about a lot of those old Destiny 1 rules.) This is an index into: DestinyTalentGridDefinition.nodes[nodeIndex].steps[stepIndex]
	StepIndex int32 `json:"stepIndex,omitempty"`
}

/* polymorph Destiny.DestinyTalentNode activationGridLevel false */

/* polymorph Destiny.DestinyTalentNode hidden false */

/* polymorph Destiny.DestinyTalentNode isActivated false */

/* polymorph Destiny.DestinyTalentNode materialsToUpgrade false */

/* polymorph Destiny.DestinyTalentNode nodeHash false */

/* polymorph Destiny.DestinyTalentNode nodeIndex false */

/* polymorph Destiny.DestinyTalentNode nodeStatsBlock false */

/* polymorph Destiny.DestinyTalentNode progressPercent false */

/* polymorph Destiny.DestinyTalentNode state false */

/* polymorph Destiny.DestinyTalentNode stepIndex false */

// Validate validates this destiny destiny talent node
func (m *DestinyDestinyTalentNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodeStatsBlock(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DestinyDestinyTalentNode) validateNodeStatsBlock(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeStatsBlock) { // not required
		return nil
	}

	if m.NodeStatsBlock != nil {

		if err := m.NodeStatsBlock.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nodeStatsBlock")
			}
			return err
		}
	}

	return nil
}

func (m *DestinyDestinyTalentNode) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DestinyDestinyTalentNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyDestinyTalentNode) UnmarshalBinary(b []byte) error {
	var res DestinyDestinyTalentNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
