// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Destiny2GetClanLeaderboardsOKBodyResponse destiny2 get clan leaderboards o k body response
// swagger:model destiny2GetClanLeaderboardsOKBodyResponse

type Destiny2GetClanLeaderboardsOKBodyResponse map[string]Destiny2GetClanLeaderboardsOKBodyResponseAdditionalProperties

// Validate validates this destiny2 get clan leaderboards o k body response
func (m Destiny2GetClanLeaderboardsOKBodyResponse) Validate(formats strfmt.Registry) error {
	return nil
}
