// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyRequestsDestinyItemTransferRequest destiny requests destiny item transfer request
// swagger:model Destiny.Requests.DestinyItemTransferRequest

type DestinyRequestsDestinyItemTransferRequest struct {

	// character Id
	CharacterID int64 `json:"characterId,omitempty"`

	// item Id
	ItemID int64 `json:"itemId,omitempty"`

	// item reference hash
	ItemReferenceHash uint32 `json:"itemReferenceHash,omitempty"`

	// membership type
	MembershipType BungieMembershipType `json:"membershipType,omitempty"`

	// stack size
	StackSize int32 `json:"stackSize,omitempty"`

	// transfer to vault
	TransferToVault bool `json:"transferToVault,omitempty"`
}

/* polymorph Destiny.Requests.DestinyItemTransferRequest characterId false */

/* polymorph Destiny.Requests.DestinyItemTransferRequest itemId false */

/* polymorph Destiny.Requests.DestinyItemTransferRequest itemReferenceHash false */

/* polymorph Destiny.Requests.DestinyItemTransferRequest membershipType false */

/* polymorph Destiny.Requests.DestinyItemTransferRequest stackSize false */

/* polymorph Destiny.Requests.DestinyItemTransferRequest transferToVault false */

// Validate validates this destiny requests destiny item transfer request
func (m *DestinyRequestsDestinyItemTransferRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMembershipType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DestinyRequestsDestinyItemTransferRequest) validateMembershipType(formats strfmt.Registry) error {

	if swag.IsZero(m.MembershipType) { // not required
		return nil
	}

	if err := m.MembershipType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("membershipType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DestinyRequestsDestinyItemTransferRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyRequestsDestinyItemTransferRequest) UnmarshalBinary(b []byte) error {
	var res DestinyRequestsDestinyItemTransferRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
