// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyDefinitionsDestinyItemQualityBlockDefinition An item's "Quality" determines its calculated stats. The Level at which the item spawns is combined with its "qualityLevel" along with some additional calculations to determine the value of those stats.
// In Destiny 2, most items don't have default item levels and quality, making this property less useful: these apparently are almost always determined by the complex mechanisms of the Reward system rather than statically. They are still provided here in case they are still useful for people. This also contains some information about Infusion.
// swagger:model Destiny.Definitions.DestinyItemQualityBlockDefinition

type DestinyDefinitionsDestinyItemQualityBlockDefinition struct {

	// The hash identifier for the infusion. It does not map to a Definition entity.
	InfusionCategoryHash uint32 `json:"infusionCategoryHash,omitempty"`

	// The string identifier for this item's "infusability", if any.
	// Items that match the same infusionCategoryName are allowed to infuse with each other.
	InfusionCategoryName string `json:"infusionCategoryName,omitempty"`

	// The "base" defined level of an item. This is a list because, in theory, each Expansion could define its own base level for an item.
	// In practice, not only was that never done in Destiny 1, but now this isn't even populated at all. When it's not populated, the level at which it spawns has to be inferred by Reward information, of which BNet receives an imperfect view and will only be reliable on instanced data as a result.
	ItemLevels []int32 `json:"itemLevels"`

	// An item can refer to pre-set level requirements. They are defined in DestinyProgressionLevelRequirementDefinition, and you can use this hash to find the appropriate definition.
	ProgressionLevelRequirementHash uint32 `json:"progressionLevelRequirementHash,omitempty"`

	// qualityLevel is used in combination with the item's level to calculate stats like Attack and Defense. It plays a role in that calculation, but not nearly as large as itemLevel does.
	QualityLevel int32 `json:"qualityLevel,omitempty"`
}

/* polymorph Destiny.Definitions.DestinyItemQualityBlockDefinition infusionCategoryHash false */

/* polymorph Destiny.Definitions.DestinyItemQualityBlockDefinition infusionCategoryName false */

/* polymorph Destiny.Definitions.DestinyItemQualityBlockDefinition itemLevels false */

/* polymorph Destiny.Definitions.DestinyItemQualityBlockDefinition progressionLevelRequirementHash false */

/* polymorph Destiny.Definitions.DestinyItemQualityBlockDefinition qualityLevel false */

// Validate validates this destiny definitions destiny item quality block definition
func (m *DestinyDefinitionsDestinyItemQualityBlockDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItemLevels(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DestinyDefinitionsDestinyItemQualityBlockDefinition) validateItemLevels(formats strfmt.Registry) error {

	if swag.IsZero(m.ItemLevels) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyItemQualityBlockDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyDefinitionsDestinyItemQualityBlockDefinition) UnmarshalBinary(b []byte) error {
	var res DestinyDefinitionsDestinyItemQualityBlockDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
