// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DestinyEntitiesVendorsDestinyVendorCategoriesComponent A vendor can have many categories of items that they sell. This component will return the category information for available items, as well as the index into those items in the user's sale item list.
// Note that, since both the category and items are indexes, this data is Content Version dependent. Be sure to check that your content is up to date before using this data. This is an unfortunate, but permanent, limitation of Vendor data.
// swagger:model Destiny.Entities.Vendors.DestinyVendorCategoriesComponent

type DestinyEntitiesVendorsDestinyVendorCategoriesComponent struct {

	// categories
	Categories DestinyEntitiesVendorsDestinyVendorCategoriesComponentCategories `json:"categories"`
}

/* polymorph Destiny.Entities.Vendors.DestinyVendorCategoriesComponent categories false */

// Validate validates this destiny entities vendors destiny vendor categories component
func (m *DestinyEntitiesVendorsDestinyVendorCategoriesComponent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DestinyEntitiesVendorsDestinyVendorCategoriesComponent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestinyEntitiesVendorsDestinyVendorCategoriesComponent) UnmarshalBinary(b []byte) error {
	var res DestinyEntitiesVendorsDestinyVendorCategoriesComponent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
