// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ForumForumRecruitmentToneLabel forum forum recruitment tone label
// swagger:model Forum.ForumRecruitmentToneLabel

type ForumForumRecruitmentToneLabel int32

// for schema
var forumForumRecruitmentToneLabelEnum []interface{}

func init() {
	var res []ForumForumRecruitmentToneLabel
	if err := json.Unmarshal([]byte(`[0,1,2]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		forumForumRecruitmentToneLabelEnum = append(forumForumRecruitmentToneLabelEnum, v)
	}
}

func (m ForumForumRecruitmentToneLabel) validateForumForumRecruitmentToneLabelEnum(path, location string, value ForumForumRecruitmentToneLabel) error {
	if err := validate.Enum(path, location, value, forumForumRecruitmentToneLabelEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this forum forum recruitment tone label
func (m ForumForumRecruitmentToneLabel) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateForumForumRecruitmentToneLabelEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
