// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ForumForumTopicsSortEnum forum forum topics sort enum
// swagger:model Forum.ForumTopicsSortEnum

type ForumForumTopicsSortEnum int32

// for schema
var forumForumTopicsSortEnumEnum []interface{}

func init() {
	var res []ForumForumTopicsSortEnum
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5,6,7]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		forumForumTopicsSortEnumEnum = append(forumForumTopicsSortEnumEnum, v)
	}
}

func (m ForumForumTopicsSortEnum) validateForumForumTopicsSortEnumEnum(path, location string, value ForumForumTopicsSortEnum) error {
	if err := validate.Enum(path, location, value, forumForumTopicsSortEnumEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this forum forum topics sort enum
func (m ForumForumTopicsSortEnum) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateForumForumTopicsSortEnumEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
