// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// GroupsV2GroupHomepage groups v2 group homepage
// swagger:model GroupsV2.GroupHomepage

type GroupsV2GroupHomepage int32

// for schema
var groupsV2GroupHomepageEnum []interface{}

func init() {
	var res []GroupsV2GroupHomepage
	if err := json.Unmarshal([]byte(`[0,1,2]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		groupsV2GroupHomepageEnum = append(groupsV2GroupHomepageEnum, v)
	}
}

func (m GroupsV2GroupHomepage) validateGroupsV2GroupHomepageEnum(path, location string, value GroupsV2GroupHomepage) error {
	if err := validate.Enum(path, location, value, groupsV2GroupHomepageEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this groups v2 group homepage
func (m GroupsV2GroupHomepage) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGroupsV2GroupHomepageEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
