// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GroupsV2GroupV2ClanInfo This contract contains clan-specific group information. It does not include any investment data.
// swagger:model GroupsV2.GroupV2ClanInfo

type GroupsV2GroupV2ClanInfo struct {

	// clan banner data
	ClanBannerData *GroupsV2ClanBanner `json:"clanBannerData,omitempty"`

	// clan callsign
	ClanCallsign string `json:"clanCallsign,omitempty"`
}

/* polymorph GroupsV2.GroupV2ClanInfo clanBannerData false */

/* polymorph GroupsV2.GroupV2ClanInfo clanCallsign false */

// Validate validates this groups v2 group v2 clan info
func (m *GroupsV2GroupV2ClanInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClanBannerData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GroupsV2GroupV2ClanInfo) validateClanBannerData(formats strfmt.Registry) error {

	if swag.IsZero(m.ClanBannerData) { // not required
		return nil
	}

	if m.ClanBannerData != nil {

		if err := m.ClanBannerData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clanBannerData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GroupsV2GroupV2ClanInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupsV2GroupV2ClanInfo) UnmarshalBinary(b []byte) error {
	var res GroupsV2GroupV2ClanInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
