// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// GroupsV2GroupDateRange groups v2 group date range
// swagger:model GroupsV2.GroupDateRange

type GroupsV2GroupDateRange int32

// for schema
var groupsV2GroupDateRangeEnum []interface{}

func init() {
	var res []GroupsV2GroupDateRange
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		groupsV2GroupDateRangeEnum = append(groupsV2GroupDateRangeEnum, v)
	}
}

func (m GroupsV2GroupDateRange) validateGroupsV2GroupDateRangeEnum(path, location string, value GroupsV2GroupDateRange) error {
	if err := validate.Enum(path, location, value, groupsV2GroupDateRangeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this groups v2 group date range
func (m GroupsV2GroupDateRange) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGroupsV2GroupDateRangeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
