// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GroupsV2GroupOptionalConversationEditRequest groups v2 group optional conversation edit request
// swagger:model GroupsV2.GroupOptionalConversationEditRequest

type GroupsV2GroupOptionalConversationEditRequest struct {

	// chat enabled
	ChatEnabled bool `json:"chatEnabled,omitempty"`

	// chat name
	ChatName string `json:"chatName,omitempty"`

	// chat security
	ChatSecurity int32 `json:"chatSecurity,omitempty"`
}

/* polymorph GroupsV2.GroupOptionalConversationEditRequest chatEnabled false */

/* polymorph GroupsV2.GroupOptionalConversationEditRequest chatName false */

/* polymorph GroupsV2.GroupOptionalConversationEditRequest chatSecurity false */

// Validate validates this groups v2 group optional conversation edit request
func (m *GroupsV2GroupOptionalConversationEditRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChatSecurity(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var groupsV2GroupOptionalConversationEditRequestTypeChatSecurityPropEnum []interface{}

func init() {
	var res []int32
	if err := json.Unmarshal([]byte(`[0,1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		groupsV2GroupOptionalConversationEditRequestTypeChatSecurityPropEnum = append(groupsV2GroupOptionalConversationEditRequestTypeChatSecurityPropEnum, v)
	}
}

// prop value enum
func (m *GroupsV2GroupOptionalConversationEditRequest) validateChatSecurityEnum(path, location string, value int32) error {
	if err := validate.Enum(path, location, value, groupsV2GroupOptionalConversationEditRequestTypeChatSecurityPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *GroupsV2GroupOptionalConversationEditRequest) validateChatSecurity(formats strfmt.Registry) error {

	if swag.IsZero(m.ChatSecurity) { // not required
		return nil
	}

	// value enum
	if err := m.validateChatSecurityEnum("chatSecurity", "body", m.ChatSecurity); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GroupsV2GroupOptionalConversationEditRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupsV2GroupOptionalConversationEditRequest) UnmarshalBinary(b []byte) error {
	var res GroupsV2GroupOptionalConversationEditRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
