// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// GroupsV2GroupMemberCountFilter groups v2 group member count filter
// swagger:model GroupsV2.GroupMemberCountFilter

type GroupsV2GroupMemberCountFilter int32

// for schema
var groupsV2GroupMemberCountFilterEnum []interface{}

func init() {
	var res []GroupsV2GroupMemberCountFilter
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		groupsV2GroupMemberCountFilterEnum = append(groupsV2GroupMemberCountFilterEnum, v)
	}
}

func (m GroupsV2GroupMemberCountFilter) validateGroupsV2GroupMemberCountFilterEnum(path, location string, value GroupsV2GroupMemberCountFilter) error {
	if err := validate.Enum(path, location, value, groupsV2GroupMemberCountFilterEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this groups v2 group member count filter
func (m GroupsV2GroupMemberCountFilter) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGroupsV2GroupMemberCountFilterEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
