// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PartnershipsPublicPartnershipDetail All the partnership info that's fit to expose externally, if we care to do so.
// swagger:model Partnerships.PublicPartnershipDetail

type PartnershipsPublicPartnershipDetail struct {

	// icon
	Icon string `json:"icon,omitempty"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// partner type
	PartnerType PartnershipsPartnershipType `json:"partnerType,omitempty"`
}

/* polymorph Partnerships.PublicPartnershipDetail icon false */

/* polymorph Partnerships.PublicPartnershipDetail identifier false */

/* polymorph Partnerships.PublicPartnershipDetail name false */

/* polymorph Partnerships.PublicPartnershipDetail partnerType false */

// Validate validates this partnerships public partnership detail
func (m *PartnershipsPublicPartnershipDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePartnerType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartnershipsPublicPartnershipDetail) validatePartnerType(formats strfmt.Registry) error {

	if swag.IsZero(m.PartnerType) { // not required
		return nil
	}

	if err := m.PartnerType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("partnerType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartnershipsPublicPartnershipDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartnershipsPublicPartnershipDetail) UnmarshalBinary(b []byte) error {
	var res PartnershipsPublicPartnershipDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
